### PR TITLE
Fix the wrong v0.0.0 version number

### PR DESCRIPTION
**Pull request by seisman**
Problem with setuptools_scm not getting correct version. PR is based on https://github.com/conda-forge/pint-feedstock/pull/34.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by weiji14** [comment]
Cool. Could you add @willschlitzer to recipe/meta.yaml too as mentioned in https://github.com/conda-forge/pygmt-feedstock/pull/14#issuecomment-779398308?

**Comment by seisman** [comment]
> Cool. Could you add @willschlitzer to recipe/meta.yaml too as mentioned in [#14 (comment)](https://github.com/conda-forge/pygmt-feedstock/pull/14#issuecomment-779398308)?

Will do it later.


The changes above still don't work. I'm wondering do we also need to add these dependencies (https://github.com/conda-forge/pint-feedstock/pull/34/files)

```
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
```

**Comment by weiji14** [comment]
Those appear to be host (i.e. build) dependencies, should be ok to add them.

**Comment by seisman** [comment]
Output from the CI job:
```
python -c 'import pygmt; pygmt.show_versions()'
PyGMT information:
  version: v0.3.0
System information:
  python: 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:34:10)  [GCC 9.3.0]
  executable: $PREFIX/bin/python
  machine: Linux-4.15.0-1106-azure-x86_64-with-glibc2.12
Dependency information:
  numpy: 1.20.1
  pandas: 1.2.2
  xarray: 0.16.2
  netCDF4: 1.5.6
  packaging: 20.9
  ghostscript: 9.53.3
  gmt: 6.1.1
GMT library information:
  binary dir: $PREFIX/bin
  cores: 2
  grid layout: rows
  library path: $PREFIX/lib/libgmt.so
  padding: 2
  plugin dir: $PREFIX/lib/gmt/plugins
  share dir: $PREFIX/share/gmt
  version: 6.1.1

```

**Review by weiji14 — APPROVED** [review]
Perfect, hopefully this is the last of the drama in release v0.3.0!

P.S. Remember to use squash and merge.

**Pull request merged**
